### ISSUE TITLE
Data Augumentation not same with BYOL?

### ISSUE THREAD

**Issue by guanfuchen** [lucidrains/pixel-level-contrastive-learning#10]
![image](https://user-images.githubusercontent.com/22321977/105275947-53649c00-5bdb-11eb-9b97-4772577efb46.png)

color jitter and gaussian kernel, sigma is not same with BYOL, does the paper use the special parameter?

**Comment by lucidrains** [comment]
@guanfuchen i'm actually using the set from SimCLR i believe, but let me check on this later and get back to you!

**Comment by lucidrains** [comment]
@guanfuchen just like my other libraries, you can customize your own augmentation functions by passing in `augment_fn` and `augment_fn2`

**Comment by guanfuchen** [comment]
I refer the other implementaion. Thxs. @lucidrains
