### ISSUE TITLE
about the pos-neg pair selection

### ISSUE THREAD

**Issue by 1144181135** [lucidrains/pixel-level-contrastive-learning#7]
Thanks for your work! I recently read your code. In the original paper, the paper skip the loss computation for cropped pairs with no overlaps, which compose only a small fraction of all the cropped pairs, which may be equivalent to the random crop of  two views need to have overlaps. Where is the corresponding code?

**Comment by lucidrains** [comment]
Here! https://github.com/lucidrains/pixel-level-contrastive-learning/blob/main/pixel_level_contrastive_learning/pixel_level_contrastive_learning.py#L424
