### ISSUE TITLE
O(n^4) memory usage in PPM

### ISSUE THREAD

**Issue by neonbjb** [lucidrains/pixel-level-contrastive-learning#8]
This line consumes an insane amount of memory:
https://github.com/lucidrains/pixel-level-contrastive-learning/blob/bf7fc8feb5684244b5afb4a261005815ead8b1a0/pixel_level_contrastive_learning/pixel_level_contrastive_learning.py#L159

As an example, trying to train a 28x28 "pixel" latent, the above attempts to allocate 75GiB of GPU memory. I was hoping to use this for far finer latents, up to 114x114 "pixels".

This einsum could be unraveled but that would be insanely expensive processing-wise. Do you or the authors have any ideas for how this could be improved?

**Comment by lucidrains** [comment]
Hi! Have you heard of a tool called Keops?

**Comment by lucidrains** [comment]
I'll try it this weekend https://www.kernel-operations.io/keops/index.html

**Comment by WilhelmT** [comment]
Would it be possible to modify the PPM so that it only aggregates locally, so that it can be used for even larger feature maps?

**Comment by neonbjb** [comment]
Great find with keops, thanks for the suggestion. I'll give it a try. I worry about the processing overhead, but it'll probably at least get me one resolution tier higher in training.

Local aggregation sounds like the better long term solution but I really need to sink my teeth into this more to make a better call there.

**Comment by lucidrains** [comment]
Sounds good, let me know how it goes! As for local aggregation, it would deviate from the paper and would be experimental. I think I'll leave it for some future paper to explore that and if there are positive results, I'll add it!

**Comment by lucidrains** [comment]
@neonbjb Hi James, want to give https://github.com/lucidrains/pixel-level-contrastive-learning/issues/8 a try?

**Comment by neonbjb** [comment]
That was fast! Sure I'll give it a try. It is missing one part: you need to replace the cosine_similarity() call with a keops call too to completely eliminate the n^4 tensor allocation. Ironically I did this part this morning but couldn't figure out the matmul part. I'll post the code here after I test it.

**Comment by lucidrains** [comment]
@neonbjb oh yes! you are right! I replaced cosine similarity as well

hopefully I did it correctly; I'm pretty new to keops still 😅

**Comment by neonbjb** [comment]
Unfortunately this doesn't work currently. sum(dim=-1) does not trigger keops to collapse a lazy tensor back into a regular one, only sum(dim=1) and sum(dim=0) do for some reason.  I need to do some more reading on how keops works to understand why.

I can fiddle around with the dims to make it work, but then run into a lib error. This occurs both on my personal machines as well as colab. I'll keep plugging away at this, but I just want to keep you abreast. :)

Here's a colab sheet you can use to play around with it live if you'd like:
https://colab.research.google.com/drive/1n-dTzli0t5lbrG8y9CWclPpgm8GGi7VO?usp=sharing

**Comment by lucidrains** [comment]
@neonbjb ok, do let me know if you figure it out! I'll circle back to this later this weekend!

**Comment by neonbjb** [comment]
The keops approach didn't end up panning out because the computational complexity was too high. My iteration rates even at moderate-sized latents were many seconds per iteration.

I have a workaround that I am testing right now. Instead of computing the pixel propagation across the entire image and then extracting out the relevant regions using torch.masked_select(), I:

1. Perform cutout & flip on images
2. Feed images through online & target predictors
3. Reverse the cutout & flip on the resulting latents
4. Extract the region between those two latents that is the same
5. Perform pixel propagation algorithm on results from (4), which is generally much smaller than the whole image.

This has allowed me to train against much larger latents, although I don't believe it aligns with the paper because step (3) necessarily causes some of the latent data to be "dropped out" when it is interpolated back down to original image size. I've had it training for a day now and results seem promising.

Thanks for your help with this & the excellent repo(s). I've learned a lot from your code. If you're at all interested in what I've done above let me know and I'll put up a PR. I'm going to close this issue since I don't think the keops approach is really acceptable and it might just be a limitation of the model if we are sticking close to the paper.

**Comment by WilhelmT** [comment]
@neonbjb Would it be possible for you to share the code you just mentioned, reversing the cutout/ratio/flip to avoid the O(n⁴)?

**Comment by neonbjb** [comment]
Sure, I am working on the code here:
https://github.com/neonbjb/DL-Art-School/blob/gan_lab/codes/models/pixel_level_contrastive_learning/pixpro_lucidrains.py

The commits on Jan 12-Jan 13 are what implement the changes. All the changes to the contrastive loss stayed inside of pixpro_lucidrains.py so you can ignore the other files:
https://github.com/neonbjb/DL-Art-School/commits/gan_lab/codes/models/pixel_level_contrastive_learning/pixpro_lucidrains.py
